# Generated by Django 4.2.4 on 2023-08-18 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleproduct',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='productapp.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapp.product'),
        ),
    ]
