# Generated by Django 4.2.4 on 2023-08-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0003_saleproduct_sale_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='product_images/download.png', upload_to='media/product_images/', verbose_name='Фото товара'),
        ),
    ]
